### ISSUE TITLE
Support for EOL versions of PHP

### ISSUE THREAD

**Issue by djmattyg007** [littlemanco/docker-apache-php#3]
Why are you providing support for EOL versions of PHP that aren't receiving any support for security patches from upstream?

**Comment by andrewhowdencom** [comment]
Thanks for the question! It's kind of cool to see someone is following along. However; beyond the scope of this work at the minute (: As soon as possible, I'll jettison them.

**Comment by andrewhowdencom** [comment]
https://github.com/littlemanco/docker-apache-php/commit/2c28a819bb9ffb2cae7954ec7151bac37418582c
